project_id = "jscmqiktfesaggpdeegk"

[functions.star-cloudprnt]
verify_jwt = true

[functions.ai-search]
verify_jwt = true

[functions.ai-translate]
verify_jwt = true

[functions.ai-chatbot]
verify_jwt = true

[functions.product-recommendations]
verify_jwt = true

[functions.generate-content]
verify_jwt = true

[functions.analyze-image]
verify_jwt = true

[functions.send-bulk-sms]
verify_jwt = true

[functions.send-sms]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.star-cloudprnt]
verify_jwt = false