project_id = "jscmqiktfesaggpdeegk"

[functions.ai-search]
verify_jwt = false

[functions.ai-translate]
verify_jwt = false

[functions.ai-chatbot]
verify_jwt = true

[functions.product-recommendations]
verify_jwt = true

[functions.generate-content]
verify_jwt = true

[functions.analyze-image]
verify_jwt = false